version: '3.2'

services:

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  yt-uploader-v2:
    image: ghcr.io/ccil-kbw/robot:latest
    restart: always
    volumes:
      - /home/seraf/.ytcreds.json:/credentials.json
    command: "/yt-upload-v2"
