version: '3.1'

services:

  monolith:
    image: ghcr.io/ccil-kbw/robot:latest-arm64
    restart: always
    ports:
      - 3333:3333
    environment:
        - MDROID_BOT_GUILD_ID=$MDROID_BOT_GUILD_ID
        - MDROID_BOT_TOKEN=$MDROID_BOT_TOKEN
        - MDROID_OBS_WEBSOCKET_HOST=127.0.0.1:4455
        - MDROID_OBS_WEBSOCKET_PASSWORD=1234567890

  watchtower:
    image: containrrr/watchtower
    platform: linux/arm64
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600

  yt-uploader-v2:
    image: ghcr.io/ccil-kbw/robot:latest
    restart: always
    volumes:
      - /home/seraf/Documents/MEGAKBW:/data
      - /home/seraf/.ytcreds.json:/credentials.json
    command: "/yt-upload-v2"
