version: '3.1'

services:

#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: postgres
#    ports:
#    - 5432:5432

  monolith:
    image: ghcr.io/ccil-kbw/robot:latest-arm64
    restart: always
    ports:
      - 3333:3333
    environment:
#        - MDROID_FEATURES_PROXY=$MDROID_FEATURES_PROXY
#        - MDROID_FEATURES_BOT=$MDROID_FEATURES_BOT
        - MDROID_BOT_GUILD_ID=$MDROID_BOT_GUILD_ID
        - MDROID_BOT_TOKEN=$MDROID_BOT_TOKEN

  watchtower:
    image: containrrr/watchtower
    platform: linux/arm64
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 600